# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/home/liming/mll_package

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/home/liming/mll_package

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/home/liming/mll_package/CMakeFiles /data/home/liming/mll_package/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/home/liming/mll_package/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mll

# Build rule for target.
mll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mll
.PHONY : mll

# fast build rule for target.
mll/fast:
	$(MAKE) -f CMakeFiles/mll.dir/build.make CMakeFiles/mll.dir/build
.PHONY : mll/fast

#=============================================================================
# Target rules for targets named mll_static

# Build rule for target.
mll_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mll_static
.PHONY : mll_static

# fast build rule for target.
mll_static/fast:
	$(MAKE) -f CMakeFiles/mll_static.dir/build.make CMakeFiles/mll_static.dir/build
.PHONY : mll_static/fast

#=============================================================================
# Target rules for targets named test_main

# Build rule for target.
test_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_main
.PHONY : test_main

# fast build rule for target.
test_main/fast:
	$(MAKE) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/build
.PHONY : test_main/fast

src/mll.o: src/mll.cpp.o
.PHONY : src/mll.o

# target to build an object file
src/mll.cpp.o:
	$(MAKE) -f CMakeFiles/mll.dir/build.make CMakeFiles/mll.dir/src/mll.cpp.o
	$(MAKE) -f CMakeFiles/mll_static.dir/build.make CMakeFiles/mll_static.dir/src/mll.cpp.o
.PHONY : src/mll.cpp.o

src/mll.i: src/mll.cpp.i
.PHONY : src/mll.i

# target to preprocess a source file
src/mll.cpp.i:
	$(MAKE) -f CMakeFiles/mll.dir/build.make CMakeFiles/mll.dir/src/mll.cpp.i
	$(MAKE) -f CMakeFiles/mll_static.dir/build.make CMakeFiles/mll_static.dir/src/mll.cpp.i
.PHONY : src/mll.cpp.i

src/mll.s: src/mll.cpp.s
.PHONY : src/mll.s

# target to generate assembly for a file
src/mll.cpp.s:
	$(MAKE) -f CMakeFiles/mll.dir/build.make CMakeFiles/mll.dir/src/mll.cpp.s
	$(MAKE) -f CMakeFiles/mll_static.dir/build.make CMakeFiles/mll_static.dir/src/mll.cpp.s
.PHONY : src/mll.cpp.s

test_main.o: test_main.c.o
.PHONY : test_main.o

# target to build an object file
test_main.c.o:
	$(MAKE) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/test_main.c.o
.PHONY : test_main.c.o

test_main.i: test_main.c.i
.PHONY : test_main.i

# target to preprocess a source file
test_main.c.i:
	$(MAKE) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/test_main.c.i
.PHONY : test_main.c.i

test_main.s: test_main.c.s
.PHONY : test_main.s

# target to generate assembly for a file
test_main.c.s:
	$(MAKE) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/test_main.c.s
.PHONY : test_main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mll"
	@echo "... mll_static"
	@echo "... rebuild_cache"
	@echo "... test_main"
	@echo "... src/mll.o"
	@echo "... src/mll.i"
	@echo "... src/mll.s"
	@echo "... test_main.o"
	@echo "... test_main.i"
	@echo "... test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

